Based on https://github.com/karpathy/micrograd/blob/master/micrograd/engine.py

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

In [3]:
from tensor import Tensor

In [4]:
inp = Tensor(np.ones((4,5),dtype=np.float32)*2.)
w = Tensor(np.ones((5,4),dtype=np.float32)*-3.)
bi = Tensor(np.ones((4,1),dtype=np.float32)*4.)
y = Tensor(np.ones((4,4),dtype=np.float32)*20.)
lr=1e-2
params = [w,bi]

In [5]:
for i in range(15):
    o = inp @ params[0] + params[1]
    loss = (o - y)**2
    print(loss.data.sum())
#     w.grad = bi.grad = 0
    loss.backward()
    params = [x - lr*x.grad for x in params]

33856.0
15655.013
7238.8794
3347.257
1547.7716
715.6899
330.9349
153.02432
70.75845
32.718678
15.1291275
6.9957247
3.234822
1.4957839
0.691654


In [6]:
o

tensor([[19.792086, 19.792086, 19.792086, 19.792086],
       [19.792086, 19.792086, 19.792086, 19.792086],
       [19.792086, 19.792086, 19.792086, 19.792086],
       [19.792086, 19.792086, 19.792086, 19.792086]], dtype=float32)

In [7]:
y

tensor([[20., 20., 20., 20.],
       [20., 20., 20., 20.],
       [20., 20., 20., 20.],
       [20., 20., 20., 20.]], dtype=float32)

In [8]:
y.data

array([[20., 20., 20., 20.],
       [20., 20., 20., 20.],
       [20., 20., 20., 20.],
       [20., 20., 20., 20.]], dtype=float32)

In [9]:
import torch

In [35]:
a = torch.tensor(np.ones((4,5),dtype=np.float32)*2.)
b = torch.tensor(np.ones((5,4),dtype=np.float32)*-3., requires_grad=True)
d = torch.tensor(np.ones((1,4),dtype=np.float32)*4., requires_grad=True)
f = torch.tensor(np.ones((4,4),dtype=np.float32)*20)

In [36]:
for i in range(15):
    e = a @ b + d
    loss = (e - f)**2
    print(loss.sum())
    loss.sum().backward()
    with torch.no_grad():
        b -= lr*b.grad
        d -= lr*d.grad
        b.grad = None
        d.grad = None

tensor(33856., grad_fn=<SumBackward0>)
tensor(15655.0137, grad_fn=<SumBackward0>)
tensor(7238.8794, grad_fn=<SumBackward0>)
tensor(3347.2573, grad_fn=<SumBackward0>)
tensor(1547.7716, grad_fn=<SumBackward0>)
tensor(715.6899, grad_fn=<SumBackward0>)
tensor(330.9349, grad_fn=<SumBackward0>)
tensor(153.0243, grad_fn=<SumBackward0>)
tensor(70.7585, grad_fn=<SumBackward0>)
tensor(32.7187, grad_fn=<SumBackward0>)
tensor(15.1291, grad_fn=<SumBackward0>)
tensor(6.9957, grad_fn=<SumBackward0>)
tensor(3.2348, grad_fn=<SumBackward0>)
tensor(1.4958, grad_fn=<SumBackward0>)
tensor(0.6917, grad_fn=<SumBackward0>)


In [37]:
e

tensor([[19.7921, 19.7921, 19.7921, 19.7921],
        [19.7921, 19.7921, 19.7921, 19.7921],
        [19.7921, 19.7921, 19.7921, 19.7921],
        [19.7921, 19.7921, 19.7921, 19.7921]], grad_fn=<AddBackward0>)

In [38]:
f

tensor([[20., 20., 20., 20.],
        [20., 20., 20., 20.],
        [20., 20., 20., 20.],
        [20., 20., 20., 20.]])

In [14]:
a = Tensor(np.array([2.,3.], dtype=np.float32))
b = Tensor(np.array([6.,4.], dtype=np.float32))

In [15]:
Q = 3*a**3 - b**2

In [16]:
o = Q.relu()*a*b

In [17]:
o.backward(np.ones_like(o))

In [18]:
a.grad

array([0.0, 1232.0], dtype=object)

In [19]:
b.grad

array([0.0, 99.0], dtype=object)

In [20]:
o.grad_fn

<function tensor.Tensor.__mul__.<locals>.grad_fn(gradient)>