Based on https://colab.research.google.com/drive/1VpeE6UvEPRz9HmsHh1KS0XxXjYu533EC?usp=sharing

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

In [3]:
import torch

In [4]:
from tensor import Tensor

In [5]:
a = Tensor(np.array([230.3], dtype=np.float32))
b = Tensor(np.array([33.2], dtype=np.float32))

In [6]:
def f(a, b):
    return (a / b - a) * (b / a + a + b) * (a - b)

In [7]:
y = f(a,b)

In [8]:
y.backward()

In [9]:
a.grad, b.grad

(array([-153284.84], dtype=float32), array([3815.0352], dtype=float32))

In [24]:
a = Tensor(np.array([1], dtype=np.float32))
b = Tensor(np.array([2], dtype=np.float32))
c = Tensor(np.array([3], dtype=np.float32))

In [19]:
a = torch.tensor(np.array([1], dtype=np.float32), requires_grad=True)
b = torch.tensor(np.array([2], dtype=np.float32), requires_grad=True)
c = torch.tensor(np.array([3], dtype=np.float32), requires_grad=True)

In [20]:
d = (a * b).sin()
e = (c - (a / b)).exp()
f = d + e
y = (f * f * f * f).log() * c
y

tensor([30.8638], grad_fn=<MulBackward0>)

In [21]:
d.retain_grad(); e.retain_grad(); f.retain_grad()

In [22]:
y.backward()

In [13]:
a.grad, b.grad, c.grad, d.grad, e.grad, f.grad

(array([-6.3461523], dtype=float32),
 array([2.4101915], dtype=float32),
 array([21.454475], dtype=float32),
 array([0.9166051], dtype=float32),
 array([0.9166051], dtype=float32),
 array([0.9166051], dtype=float32))

In [23]:
a.grad, b.grad, c.grad, d.grad, e.grad, f.grad

(tensor([-6.3462]),
 tensor([2.4102]),
 tensor([21.4545]),
 tensor([0.9166]),
 tensor([0.9166]),
 tensor([0.9166]))

In [65]:
a = Tensor(np.array([2], dtype=np.float32))

In [49]:
a = torch.tensor(np.array([2], dtype=np.float32), requires_grad=True)

In [66]:
b = a.sin()
c = a.log()
d = c*b*a
e = c*d*a

In [67]:
e

tensor([1.7474986], dtype=float32)

In [52]:
b.retain_grad(); c.retain_grad(); d.retain_grad(); e.retain_grad()

In [68]:
e.backward()

In [69]:
a.grad, b.grad, c.grad, d.grad, e.grad

(array([2.2082963], dtype=float32),
 array([1.921812], dtype=float32),
 array([5.0422153], dtype=float32),
 array([1.3862944], dtype=float32),
 array([1.], dtype=float32))

In [54]:
a.grad, b.grad, c.grad, d.grad, e.grad

(tensor([3.4689]),
 tensor([1.9218]),
 tensor([5.0422]),
 tensor([1.3863]),
 tensor([1.]))