Based on https://colab.research.google.com/drive/1VpeE6UvEPRz9HmsHh1KS0XxXjYu533EC?usp=sharing

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

In [3]:
import torch

In [4]:
from tensor import Tensor

In [5]:
a = Tensor(np.array([230.3], dtype=np.float32))
b = Tensor(np.array([33.2], dtype=np.float32))

In [6]:
def f(a, b):
    return (a / b - a) * (b / a + a + b) * (a - b)

In [7]:
y = f(a,b)

In [8]:
y.backward()

In [9]:
a.grad, b.grad

(array([-153284.84], dtype=float32), array([3815.0352], dtype=float32))

In [19]:
a = Tensor(np.array([43], dtype=np.float32))
b = Tensor(np.array([3], dtype=np.float32))
c = Tensor(np.array([2], dtype=np.float32))

In [33]:
a = torch.tensor(np.array([43], dtype=np.float32), requires_grad=True)
b = torch.tensor(np.array([3], dtype=np.float32), requires_grad=True)
c = torch.tensor(np.array([2], dtype=np.float32), requires_grad=True)

In [34]:
d = (a * b).sin()
e = (c - (a / b)).exp()
f = d + e
y = (f ** 2).log() * c
y

tensor([-6.5706], grad_fn=<MulBackward0>)

In [35]:
d.retain_grad(); e.retain_grad(); f.retain_grad()

In [36]:
y.backward()

In [31]:
a.grad, b.grad, c.grad, d.grad, e.grad, f.grad

(tensor([60.8535]),
 tensor([872.2331]),
 tensor([-3.2854]),
 tensor([-20.6751]),
 tensor([-20.6751]),
 tensor([-20.6751]))

In [18]:
a.grad, b.grad, c.grad, d.grad, e.grad, f.grad

(tensor([60.8535]),
 tensor([872.2331]),
 tensor([-3.2854]),
 tensor([-20.6751]),
 tensor([-20.6751]),
 tensor([-20.6751]))